### ISSUE TITLE
Avast - False Positive Issue

### ISSUE THREAD

**Issue by DeadlyDad** [viktor-ferenczi/performance-improvements#32]
![image](https://user-images.githubusercontent.com/13209333/166168287-b8b405ce-f85d-4c52-9c38-2e1102cc9cea.png)

I just had this popup.  Please investigate.  I'm assuming that it is a false positive, but want to be sure.  Here is the VirusTotal report on the file: https://www.virustotal.com/gui/file/f43d903e40e74c597fcd8117f1a6e0d3a7a8ec5b33fb7371ea2f1292d0623597/detection

**Comment by viktor-ferenczi** [comment]
Client or server plugin? 

In case of client plugins the source code from GitHub is compiled on your machine, so no binary is delivered directly. It pretty much guarantees that there is no malware, since the source code compiled is publicly available and reviewed.

In case of a server plugin I publish binary releases. I have a paid antivirus (Bitdefender) myself, so publishing a virus in a server plugin is also unlikely (but not completely impossible).

**Comment by viktor-ferenczi** [comment]
However, reviewing your screenshot once more I noticed that the detection was in a cached precompiled mod file (assembly). These files are actually DLLs, but stored with the file extension .cache. These are produced and loaded at runtime by the plugin.

You can try one or more of these mitigations:
- Delete the `Cache` folder and let the game regenerate on on world load.
- Exclude the `Cache` folder in Avast from scanning.
- Disable the `Cache compiled mods` option in the plugin's configuration. (It can be reached via the Plugins dialog.)

Please let me know if the above worked.

**Comment by DeadlyDad** [comment]
Client plugin.  As the VT report came back completely negative, I just made an exception in Avast and kept on truckin'.
